/** v2 export remapped onto current presets (Rare ×0.25, Often ×2, Favorite ×5). */
export const CHRIS_PROFILE_ID = "chris";
export const CHRIS_PROFILE_NAME = "Chris";

export const WRISTAKER_PROFILE_ID = "wristaker";
export const WRISTAKER_PROFILE_NAME = "Wristaker";

/** Last refresh of Chris / Wristaker seed weights (from profiles export). */
export const SEED_PROFILES_UPDATED_AT = "2026-09-02";
export const SEED_PROFILES_UPDATED_MS = Date.parse("2026-09-02T08:30:24.246Z");

/** P1 → Chris, P2 → Wristaker when a slot has no assignment. */
export function defaultPlayerProfileId(playerIndex: number): string | null {
  if (playerIndex === 0) return CHRIS_PROFILE_ID;
  if (playerIndex === 1) return WRISTAKER_PROFILE_ID;
  return null;
}

export const CHRIS_WEIGHTS: Record<string, number> = {
  mario: 0,
  "donkey-kong": 1,
  link: 0.25,
  samus: 1,
  "dark-samus": 1,
  yoshi: 0,
  kirby: 2,
  fox: 1,
  pikachu: 1,
  luigi: 0.25,
  ness: 1,
  "captain-falcon": 2,
  jigglypuff: 0,
  peach: 0.25,
  daisy: 0.1,
  bowser: 1,
  "ice-climbers": 1,
  sheik: 1,
  zelda: 2,
  "dr-mario": 2,
  pichu: 0,
  falco: 1,
  marth: 1,
  lucina: 1,
  "young-link": 0.25,
  ganondorf: 1,
  mewtwo: 5,
  roy: 0,
  chrom: 0,
  "mr-game-watch": 0.25,
  "meta-knight": 0.25,
  pit: 1,
  "dark-pit": 1,
  "zero-suit-samus": 1,
  wario: 1,
  snake: 0,
  ike: 1,
  "pokemon-trainer": 5,
  "diddy-kong": 0.25,
  lucas: 1,
  sonic: 1,
  "king-dedede": 1,
  olimar: 0,
  lucario: 1,
  rob: 1,
  "toon-link": 0,
  wolf: 1,
  villager: 1,
  "mega-man": 0,
  "wii-fit-trainer": 1,
  rosalina: 1,
  "little-mac": 0.25,
  greninja: 1,
  "mii-brawler": 1,
  "mii-swordfighter": 1,
  "mii-gunner": 1,
  palutena: 1,
  "pac-man": 1,
  robin: 0,
  shulk: 0.5,
  "bowser-jr": 1,
  "duck-hunt": 1,
  ryu: 0.25,
  ken: 0,
  cloud: 0,
  corrin: 2,
  bayonetta: 1,
  inkling: 1,
  ridley: 1,
  simon: 0.25,
  richter: 0.25,
  "king-k-rool": 1,
  isabelle: 0,
  incineroar: 3,
  "piranha-plant": 2,
  joker: 1,
  hero: 2,
  "banjo-kazooie": 5,
  terry: 1,
  byleth: 1,
  "min-min": 0,
  steve: 2,
  sephiroth: 0,
  "pyra-mythra": 2,
  kazuya: 0.25,
  sora: 1,
};

export const WRISTAKER_WEIGHTS: Record<string, number> = {
  mario: 5,
  "donkey-kong": 5,
  link: 1,
  samus: 1,
  "dark-samus": 0.25,
  yoshi: 0.25,
  kirby: 1,
  fox: 0.25,
  pikachu: 1,
  luigi: 0.25,
  ness: 1,
  "captain-falcon": 5,
  jigglypuff: 0,
  peach: 2,
  daisy: 1,
  bowser: 5,
  "ice-climbers": 1,
  sheik: 0.25,
  zelda: 0.5,
  "dr-mario": 0.25,
  pichu: 1,
  falco: 0.25,
  marth: 1,
  lucina: 0.25,
  "young-link": 1,
  ganondorf: 5,
  mewtwo: 1,
  roy: 0.25,
  chrom: 1,
  "mr-game-watch": 0.25,
  "meta-knight": 1,
  pit: 1,
  "dark-pit": 1,
  "zero-suit-samus": 0,
  wario: 1,
  snake: 0.25,
  ike: 1,
  "pokemon-trainer": 0.25,
  "diddy-kong": 1,
  lucas: 0.25,
  sonic: 1,
  "king-dedede": 2,
  olimar: 1,
  lucario: 0.25,
  rob: 1,
  "toon-link": 0.25,
  wolf: 1,
  villager: 0.25,
  "mega-man": 1,
  "wii-fit-trainer": 1,
  rosalina: 1,
  "little-mac": 5,
  greninja: 0,
  "mii-brawler": 0.25,
  "mii-swordfighter": 1,
  "mii-gunner": 0.25,
  palutena: 1,
  "pac-man": 0.25,
  robin: 1,
  shulk: 0.25,
  "bowser-jr": 1,
  "duck-hunt": 1,
  ryu: 1,
  ken: 2,
  cloud: 5,
  corrin: 1,
  bayonetta: 1,
  inkling: 0,
  ridley: 5,
  simon: 1,
  richter: 1,
  "king-k-rool": 2,
  isabelle: 0,
  incineroar: 2,
  "piranha-plant": 0.25,
  joker: 0,
  hero: 0,
  "banjo-kazooie": 0.25,
  terry: 5,
  byleth: 2,
  "min-min": 0.25,
  steve: 0,
  sephiroth: 5,
  "pyra-mythra": 5,
  kazuya: 5,
  sora: 0.25,
};
